spring.application.name=Project
spring.datasource.url=jdbc:mysql://localhost:3306/Project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# jwt
spring.jwt.secret-key=asdfghjklzxcvbnmqrtyuiop123456789012345
spring.jwt.expiration=90000000
spring.jwt.refresh-expiration=86400000

cloudinary.cloud-name=dabc123xyz
cloudinary.api-key=123456789012345
cloudinary.api-secret=abcdefghijklmnopqrstuvwxyz
